### ISSUE TITLE
[frontend] Unable to expose environment variables to frontend build

### ISSUE THREAD

**Issue by kwajiehao** [opengovsg/ts-template#2624]
## Problem

Currently, ts-template uses a separate [`deploy` repo](https://github.com/opengovsg/deploy) to deploy to AWS. This repo contains GitHub workflows which build and deploy to AWS. The problem is that we are unable to modify the build configuration for the build and deploy steps because they are defined in this repo to be used with all ts-template projects.

The relevant code can be found in this [workflow file](https://github.com/opengovsg/deploy/blob/develop/.github/workflows/aws.yml):

```
      - name: Push image to ECR
        id: push-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ecr-repository }}
          IMAGE_TAG: ${{ inputs.image-tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
```

This is a problem in particular for frontend projects which want to use non-secret frontend environment variables (such as for Supabase, Datadog RUM, etc.) because we are unable to specify build arguments to the Docker build step. 

## Expected behavior
There should be an easy way for projects using ts-template to expose frontend env vars in the frontend build step
